                                      Cognifyz: Internship Program in the field of Data Science

In [ ]:
LEVEL2- TASK3:  Feature Engineering

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set(color_codes=True)
%matplotlib inline 
import warnings
warnings.filterwarnings("ignore")

file_path = r"E:\COLLEGGE\6 SEMESTER\Internship cognifyz\Dataset .csv"


try:
     dataset = pd.read_csv(file_path, sep=",", on_bad_lines='skip', encoding="utf-8-sig")
     print("FILE READ SUCESSFULLY")
except FileNotFoundError:
     print(f"File not found: {file_path}")

FILE READ SUCESSFULLY

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [6]:
dataset.head(2)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591

 Extract additional features from the existing
 columns, such as the length of the restaurant
 name or address.

In [8]:
dataset["Address Length"]=dataset["Address"].apply(lambda x: len(str(x)))
dataset["Restaurant Name Length"]=dataset["Restaurant Name"].apply(lambda x: len(str(x)))

dataset[["Restaurant Name","Restaurant Name Length","Address","Address Length"]]

,Restaurant Name,Restaurant Name Length,Address,Address Length
0,Le Petit Souffle,16,"Third Floor, Century City Mall, Kalayaan Avenu...",71
1,Izakaya Kikufuji,16,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...",67
2,Heat - Edsa Shangri-La,22,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...",56
3,Ooma,4,"Third Floor, Mega Fashion Hall, SM Megamall, O...",70
4,Sambo Kojin,11,"Third Floor, Mega Atrium, SM Megamall, Ortigas...",64
...,...,...,...,...
9546,Naml۱ Gurme,11,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",103
9547,Ceviz A��ac۱,12,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",77
9548,Huqqa,5,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",73
9549,A���k Kahve,11,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",75
9550,Walter's Coffee Roastery,24,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",65

Create new features like "Has Table Booking"
 or "Has Online Delivery" by encoding
 categorical variables

In [10]:
#Feature Engineering Part II:Create new features like "Has Table Booking"or "Has Online Delivery" by encoding
 #categorical variables.
dataset["Categ_Has Table booking"]=dataset["Has Table booking"].apply(lambda x: 1 if x=="Yes" else 0)
dataset["Categ_Has Online delivery"]=dataset["Has Online delivery"].apply(lambda x: 1 if x=="Yes" else 0)

dataset[["Has Table booking","Categ_Has Table booking","Has Online delivery","Categ_Has Table booking"]]

,Has Table booking,Categ_Has Table booking,Has Online delivery,Categ_Has Table booking
0,Yes,1,No,1
1,Yes,1,No,1
2,Yes,1,No,1
3,No,0,No,0
4,Yes,1,No,1
...,...,...,...,...
9546,No,0,No,0
9547,No,0,No,0
9548,No,0,No,0
9549,No,0,No,0
9550,No,0,No,0